include:
  - path: postgres/compose.yaml
    env_file: .env

services:
      
  web1:
    restart: on-failure
    build: ./web
    hostname: web1
    environment:
      - SERVER_PORT=$SERVER_PORT 
      - NODE_ENV=$MODE
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PW=$POSTGRES_PW
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
    expose:
      - $SERVER_PORT
    depends_on:
      - master
      - apprentice
    networks:
      - db-net
      - front-net

  web2:
    restart: on-failure
    build: ./web
    hostname: web2
    environment:
      - SERVER_PORT=$SERVER_PORT 
      - NODE_ENV=$MODE
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PW=$POSTGRES_PW
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_HOST=$POSTGRES_HOST
    expose:
      - $SERVER_PORT
    depends_on:
      - master
      - apprentice
    networks:
      - db-net
      - front-net

  nginx:
    build: ./nginx
    environment:
      - SERVER_PORT=$SERVER_PORT
    ports:
    - '80:80'
    - '443:443'
    depends_on:
    - web1
    - web2
    networks:
    - front-net
    restart: on-failure

networks:
  db-net:
    driver: bridge
  front-net: